import random
from decimal import Decimal

from sqlalchemy import select

from app.core.database import SessionLocal
from app.core.security import get_password_hash
from app.models.enums import Currency, OperationType, OwnerType, PricePeriod, PropertyStatus, PropertyType, UserRole
from app.models.image import PropertyImage
from app.models.property import Property
from app.models.user import User

OWNERS = [
    {
        "full_name": "Alisher Toshmatov",
        "phone": "+998901234567",
        "email": "alisher@mail.uz",
        "telegram": "alisher_t",
    },
    {
        "full_name": "Malika Raximova",
        "phone": "+998935551122",
        "email": "malika@mail.uz",
        "telegram": "malika_r",
    },
    {
        "full_name": "Jahongir Karimov",
        "phone": "+998977778899",
        "email": "jahon@mail.uz",
        "telegram": "",
    },
    {
        "full_name": "Nilufar Abdullayeva",
        "phone": "+998909991122",
        "email": "nilufar@mail.uz",
        "telegram": "nilufar_a",
    },
    {
        "full_name": "Bobur Xasanov",
        "phone": "+998998880011",
        "email": "bobur@mail.uz",
        "telegram": "",
    },
]

SEED_PROPERTIES = [
    {
        "title": "2 xonali kvartira, Yunusobod",
        "price": Decimal("72000"),
        "region": "Toshkent",
        "district": "Yunusobod",
        "rooms": 2,
        "area_m2": 58,
        "floor": 5,
        "total_floors": 9,
        "property_type": PropertyType.apartment,
        "repair_type": "Yaxshi remont",
        "operation_type": OperationType.sale,
        "latitude": 41.34,
        "longitude": 69.31,
        "views_count": 234,
        "image": "https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?w=600&h=400&fit=crop&auto=format",
        "amenities": ["lift", "parkovka", "metro_yaqin", "maktab_yaqin", "balkon", "konditsioner"],
    },
    {
        "title": "3 xonali kvartira, Chilonzor",
        "price": Decimal("89000"),
        "region": "Toshkent",
        "district": "Chilonzor",
        "rooms": 3,
        "area_m2": 76,
        "floor": 3,
        "total_floors": 9,
        "property_type": PropertyType.apartment,
        "repair_type": "Kapital remont",
        "operation_type": OperationType.sale,
        "latitude": 41.29,
        "longitude": 69.21,
        "views_count": 512,
        "image": "https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?w=600&h=400&fit=crop&auto=format",
        "amenities": ["lift", "parkovka", "balkon", "konditsioner"],
    },
    {
        "title": "Tijoriy maydon, Yakkasaroy",
        "price": Decimal("2500"),
        "region": "Toshkent",
        "district": "Yakkasaroy",
        "rooms": 0,
        "area_m2": 140,
        "floor": 1,
        "total_floors": 5,
        "property_type": PropertyType.commercial,
        "repair_type": "Ofis remont",
        "operation_type": OperationType.rent,
        "price_period": PricePeriod.month,
        "latitude": 41.30,
        "longitude": 69.28,
        "views_count": 178,
        "image": "https://images.unsplash.com/photo-1497366216548-37526070297c?w=600&h=400&fit=crop&auto=format",
        "amenities": ["parkovka", "konditsioner"],
    },
    {
        "title": "1 xonali kvartira, Mirzo Ulugbek",
        "price": Decimal("45000"),
        "region": "Toshkent",
        "district": "Mirzo Ulugbek",
        "rooms": 1,
        "area_m2": 34,
        "floor": 2,
        "total_floors": 5,
        "property_type": PropertyType.apartment,
        "repair_type": "Evroremont",
        "operation_type": OperationType.sale,
        "latitude": 41.33,
        "longitude": 69.30,
        "views_count": 89,
        "image": "https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?w=600&h=400&fit=crop&auto=format",
        "amenities": ["lift", "metro_yaqin", "balkon", "24_7_qoriklash"],
    },
    {
        "title": "Xususiy uy, Sergeli",
        "price": Decimal("120000"),
        "region": "Toshkent",
        "district": "Sergeli",
        "rooms": 5,
        "area_m2": 200,
        "floor": 1,
        "total_floors": 2,
        "property_type": PropertyType.house,
        "repair_type": "Yaxshi remont",
        "operation_type": OperationType.sale,
        "latitude": 41.24,
        "longitude": 69.23,
        "views_count": 320,
        "image": "https://images.unsplash.com/photo-1583608205776-bfd35f0d9f83?w=600&h=400&fit=crop&auto=format",
        "amenities": ["parkovka", "bolalar_maydoni", "maktab_yaqin"],
    },
    {
        "title": "Yangi bino 2 xonali, Mirobod",
        "price": Decimal("95000"),
        "region": "Toshkent",
        "district": "Mirobod",
        "rooms": 2,
        "area_m2": 65,
        "floor": 7,
        "total_floors": 16,
        "property_type": PropertyType.new_building,
        "repair_type": "Qora quti",
        "operation_type": OperationType.sale,
        "latitude": 41.31,
        "longitude": 69.29,
        "views_count": 405,
        "image": "https://images.unsplash.com/photo-1545324418-cc1a3fa10c00?w=600&h=400&fit=crop&auto=format",
        "amenities": ["lift", "parkovka", "metro_yaqin", "konditsioner", "balkon"],
    },
    {
        "title": "3 xonali kvartira, Olmazor",
        "price": Decimal("78000"),
        "region": "Toshkent",
        "district": "Olmazor",
        "rooms": 3,
        "area_m2": 68,
        "floor": 4,
        "total_floors": 9,
        "property_type": PropertyType.apartment,
        "repair_type": "Yaxshi remont",
        "operation_type": OperationType.sale,
        "latitude": 41.28,
        "longitude": 69.21,
        "views_count": 156,
        "image": "https://images.unsplash.com/photo-1560185007-cde436f6a4d0?w=600&h=400&fit=crop&auto=format",
        "amenities": ["lift", "maktab_yaqin", "bolalar_maydoni"],
    },
    {
        "title": "Ijara 1 xonali, Chilonzor",
        "price": Decimal("350"),
        "region": "Toshkent",
        "district": "Chilonzor",
        "rooms": 1,
        "area_m2": 30,
        "floor": 2,
        "total_floors": 5,
        "property_type": PropertyType.apartment,
        "repair_type": "Kapital remont",
        "operation_type": OperationType.rent,
        "price_period": PricePeriod.month,
        "latitude": 41.28,
        "longitude": 69.20,
        "views_count": 670,
        "image": "https://images.unsplash.com/photo-1560185127-6ed189bf02f4?w=600&h=400&fit=crop&auto=format",
        "amenities": ["parkovka", "metro_yaqin", "balkon"],
    },
    {
        "title": "Yer maydoni, Bektemir",
        "price": Decimal("55000"),
        "region": "Toshkent",
        "district": "Bektemir",
        "rooms": 0,
        "area_m2": 600,
        "floor": 1,
        "total_floors": 1,
        "property_type": PropertyType.land,
        "repair_type": "",
        "operation_type": OperationType.sale,
        "latitude": 41.22,
        "longitude": 69.26,
        "views_count": 47,
        "image": "https://images.unsplash.com/photo-1500382017468-9049fed747ef?w=600&h=400&fit=crop&auto=format",
        "amenities": [],
    },
    {
        "title": "Studiya kvartira, Yashnobod",
        "price": Decimal("35000"),
        "region": "Toshkent",
        "district": "Yashnobod",
        "rooms": 1,
        "area_m2": 28,
        "floor": 3,
        "total_floors": 12,
        "property_type": PropertyType.apartment,
        "repair_type": "Evroremont",
        "operation_type": OperationType.sale,
        "latitude": 41.32,
        "longitude": 69.25,
        "views_count": 112,
        "image": "https://images.unsplash.com/photo-1586023492125-27b2c045efd7?w=600&h=400&fit=crop&auto=format",
        "amenities": ["lift", "metro_yaqin", "24_7_qoriklash"],
    },
    {
        "title": "4 xonali kvartira, Yunusobod",
        "price": Decimal("135000"),
        "region": "Toshkent",
        "district": "Yunusobod",
        "rooms": 4,
        "area_m2": 96,
        "floor": 8,
        "total_floors": 12,
        "property_type": PropertyType.apartment,
        "repair_type": "Kapital remont",
        "operation_type": OperationType.sale,
        "latitude": 41.36,
        "longitude": 69.29,
        "views_count": 289,
        "image": "https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?w=600&h=400&fit=crop&auto=format",
        "amenities": ["lift", "parkovka", "metro_yaqin", "balkon", "konditsioner", "bolalar_maydoni"],
    },
    {
        "title": "Tijoriy maydon, Chilonzor",
        "price": Decimal("1800"),
        "region": "Toshkent",
        "district": "Chilonzor",
        "rooms": 0,
        "area_m2": 85,
        "floor": 2,
        "total_floors": 4,
        "property_type": PropertyType.commercial,
        "repair_type": "Ofis remont",
        "operation_type": OperationType.rent,
        "price_period": PricePeriod.month,
        "latitude": 41.27,
        "longitude": 69.22,
        "views_count": 92,
        "image": "https://images.unsplash.com/photo-1497366811353-6870744d04b2?w=600&h=400&fit=crop&auto=format",
        "amenities": ["parkovka", "konditsioner"],
    },
    {
        "title": "Yangi bino, Yakkasaroy",
        "price": Decimal("115000"),
        "region": "Toshkent",
        "district": "Yakkasaroy",
        "rooms": 3,
        "area_m2": 82,
        "floor": 5,
        "total_floors": 14,
        "property_type": PropertyType.new_building,
        "repair_type": "Qora quti",
        "operation_type": OperationType.sale,
        "latitude": 41.30,
        "longitude": 69.27,
        "views_count": 198,
        "image": "https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?w=600&h=400&fit=crop&auto=format",
        "amenities": ["lift", "parkovka", "metro_yaqin", "maktab_yaqin", "24_7_qoriklash"],
    },
    {
        "title": "Xususiy uy, Olmazor",
        "price": Decimal("180000"),
        "region": "Toshkent",
        "district": "Olmazor",
        "rooms": 6,
        "area_m2": 350,
        "floor": 1,
        "total_floors": 2,
        "property_type": PropertyType.house,
        "repair_type": "Kapital remont",
        "operation_type": OperationType.sale,
        "latitude": 41.26,
        "longitude": 69.19,
        "views_count": 73,
        "image": "https://images.unsplash.com/photo-1600585154340-be6161a56a0c?w=600&h=400&fit=crop&auto=format",
        "amenities": ["parkovka", "bolalar_maydoni", "maktab_yaqin", "balkon"],
    },
    {
        "title": "Ijara 2 xonali, Mirobod",
        "price": Decimal("500"),
        "region": "Toshkent",
        "district": "Mirobod",
        "rooms": 2,
        "area_m2": 55,
        "floor": 4,
        "total_floors": 7,
        "property_type": PropertyType.apartment,
        "repair_type": "Yaxshi remont",
        "operation_type": OperationType.rent,
        "price_period": PricePeriod.month,
        "latitude": 41.32,
        "longitude": 69.28,
        "views_count": 445,
        "image": "https://images.unsplash.com/photo-1560185007-5f0bb1866cab?w=600&h=400&fit=crop&auto=format",
        "amenities": ["lift", "parkovka", "metro_yaqin", "konditsioner"],
    },
    {
        "title": "Yer maydoni, Sergeli",
        "price": Decimal("45000"),
        "region": "Toshkent",
        "district": "Sergeli",
        "rooms": 0,
        "area_m2": 800,
        "floor": 1,
        "total_floors": 1,
        "property_type": PropertyType.land,
        "repair_type": "",
        "operation_type": OperationType.sale,
        "latitude": 41.23,
        "longitude": 69.24,
        "views_count": 31,
        "image": "https://images.unsplash.com/photo-1500382017468-9049fed747ef?w=600&h=400&fit=crop&auto=format",
        "amenities": [],
    },
    {
        "title": "2 xonali kvartira, Uchtepa",
        "price": Decimal("62000"),
        "region": "Toshkent",
        "district": "Uchtepa",
        "rooms": 2,
        "area_m2": 50,
        "floor": 1,
        "total_floors": 5,
        "property_type": PropertyType.apartment,
        "repair_type": "Yaxshi remont",
        "operation_type": OperationType.sale,
        "latitude": 41.27,
        "longitude": 69.17,
        "views_count": 134,
        "image": "https://images.unsplash.com/photo-1560185007-5f0bb1866cab?w=600&h=400&fit=crop&auto=format",
        "amenities": ["maktab_yaqin", "bolalar_maydoni"],
    },
    {
        "title": "Yangi bino 3 xonali, Mirzo Ulugbek",
        "price": Decimal("140000"),
        "region": "Toshkent",
        "district": "Mirzo Ulugbek",
        "rooms": 3,
        "area_m2": 90,
        "floor": 9,
        "total_floors": 18,
        "property_type": PropertyType.new_building,
        "repair_type": "Qora quti",
        "operation_type": OperationType.sale,
        "latitude": 41.34,
        "longitude": 69.32,
        "views_count": 267,
        "image": "https://images.unsplash.com/photo-1600585152220-90363fe7e115?w=600&h=400&fit=crop&auto=format",
        "amenities": ["lift", "parkovka", "metro_yaqin", "maktab_yaqin", "24_7_qoriklash", "bolalar_maydoni"],
    },
    {
        "title": "Studio, Shayxontohur",
        "price": Decimal("28000"),
        "region": "Toshkent",
        "district": "Shayxontohur",
        "rooms": 1,
        "area_m2": 25,
        "floor": 2,
        "total_floors": 6,
        "property_type": PropertyType.apartment,
        "repair_type": "Evroremont",
        "operation_type": OperationType.sale,
        "latitude": 41.29,
        "longitude": 69.26,
        "views_count": 201,
        "image": "https://images.unsplash.com/photo-1586023492125-27b2c045efd7?w=600&h=400&fit=crop&auto=format",
        "amenities": ["lift", "metro_yaqin"],
    },
    {
        "title": "Xususiy uy, Bektemir",
        "price": Decimal("95000"),
        "region": "Toshkent",
        "district": "Bektemir",
        "rooms": 4,
        "area_m2": 180,
        "floor": 1,
        "total_floors": 1,
        "property_type": PropertyType.house,
        "repair_type": "Oddiy remont",
        "operation_type": OperationType.sale,
        "latitude": 41.21,
        "longitude": 69.27,
        "views_count": 55,
        "image": "https://images.unsplash.com/photo-1583608205776-bfd35f0d9f83?w=600&h=400&fit=crop&auto=format",
        "amenities": ["parkovka", "maktab_yaqin"],
    },
    {
        "title": "Ijara 3 xonali, Yashnobod",
        "price": Decimal("600"),
        "region": "Toshkent",
        "district": "Yashnobod",
        "rooms": 3,
        "area_m2": 70,
        "floor": 5,
        "total_floors": 9,
        "property_type": PropertyType.apartment,
        "repair_type": "Kapital remont",
        "operation_type": OperationType.rent,
        "price_period": PricePeriod.month,
        "latitude": 41.32,
        "longitude": 69.24,
        "views_count": 188,
        "image": "https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?w=600&h=400&fit=crop&auto=format",
        "amenities": ["lift", "parkovka", "balkon", "konditsioner", "metronet"],
    },
]


def seed() -> None:
    db = SessionLocal()
    try:
        if db.scalar(select(User).where(User.email == "admin@uymap.uz")):
            return

        admin = User(
            full_name="UyMap Admin",
            phone="+998901111111",
            email="admin@uymap.uz",
            role=UserRole.ADMIN,
            hashed_password=get_password_hash("admin12345"),
        )
        db.add(admin)
        db.flush()

        owners = []
        for o in OWNERS:
            user = User(
                full_name=o["full_name"],
                phone=o["phone"],
                email=o["email"],
                telegram=o["telegram"],
                region="Toshkent",
                district=random.choice([
                    "Yunusobod", "Chilonzor", "Mirzo Ulugbek", "Mirobod",
                    "Sergeli", "Olmazor", "Uchtepa", "Yashnobod", "Yakkasaroy",
                ]),
                role=UserRole.OWNER,
                hashed_password=get_password_hash("owner12345"),
            )
            db.add(user)
            owners.append(user)
        db.flush()

        for idx, item in enumerate(SEED_PROPERTIES):
            image = item.pop("image")
            owner = owners[idx % len(owners)]
            is_premium = idx % 3 != 0
            is_verified = idx % 5 != 1
            prop = Property(
                **item,
                description="UyMap.uz orqali joylangan tekshirilgan e'lon. Barcha asosiy qulayliklar va aloqa ma'lumotlari mavjud.",
                currency=Currency.USD,
                owner_type=OwnerType.owner,
                status=PropertyStatus.active,
                is_verified=is_verified,
                is_premium=is_premium,
                owner_id=owner.id,
            )
            db.add(prop)
            db.flush()
            db.add(PropertyImage(property_id=prop.id, url=image, is_main=True, sort_order=0))

        db.commit()
        print(f"Seed data created: {len(SEED_PROPERTIES)} properties, {len(OWNERS)} owners, 1 admin")
        print("Admin: admin@uymap.uz / admin12345")
        print("Owners: alisher@mail.uz, malika@mail.uz, jahon@mail.uz, nilufar@mail.uz, bobur@mail.uz / owner12345")
    finally:
        db.close()


if __name__ == "__main__":
    seed()
