"""add_metro_station

Revision ID: a3b9c8a9a621
Revises: 0001_initial
Create Date: 2026-06-19 19:16:03.078762
"""
from alembic import op
import sqlalchemy as sa


revision = 'a3b9c8a9a621'
down_revision = '0001_initial'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('properties', sa.Column('metro_station', sa.String(length=120), nullable=True))
    op.create_index(op.f('ix_properties_metro_station'), 'properties', ['metro_station'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_properties_metro_station'), table_name='properties')
    op.drop_column('properties', 'metro_station')
    # ### end Alembic commands ###
