"""add_company_profile_building_fields

Revision ID: c69a18479a4f
Revises: d8f6e3c2a1b0
Create Date: 2026-06-19 20:05:01.005321
"""
from alembic import op
import sqlalchemy as sa


revision = 'c69a18479a4f'
down_revision = 'd8f6e3c2a1b0'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('company_profiles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('company_name', sa.String(length=255), nullable=False),
    sa.Column('license_number', sa.String(length=100), nullable=False),
    sa.Column('company_phone', sa.String(length=40), nullable=False),
    sa.Column('company_address', sa.String(length=255), nullable=False),
    sa.Column('company_description', sa.Text(), nullable=False),
    sa.Column('logo_url', sa.String(length=500), nullable=True),
    sa.Column('documents', sa.JSON(), nullable=False),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_company_profiles_id'), 'company_profiles', ['id'], unique=False)
    op.create_index(op.f('ix_company_profiles_user_id'), 'company_profiles', ['user_id'], unique=True)
    op.add_column('buildings', sa.Column('total_apartments', sa.Integer(), nullable=False))
    op.add_column('buildings', sa.Column('property_type', sa.String(length=50), nullable=False))
    op.add_column('buildings', sa.Column('building_material', sa.String(length=100), nullable=True))
    op.add_column('buildings', sa.Column('parking_type', sa.String(length=100), nullable=True))
    op.add_column('buildings', sa.Column('elevator_count', sa.Integer(), nullable=True))
    op.add_column('buildings', sa.Column('images', sa.JSON(), nullable=False))
    op.add_column('buildings', sa.Column('amenities', sa.JSON(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('buildings', 'amenities')
    op.drop_column('buildings', 'images')
    op.drop_column('buildings', 'elevator_count')
    op.drop_column('buildings', 'parking_type')
    op.drop_column('buildings', 'building_material')
    op.drop_column('buildings', 'property_type')
    op.drop_column('buildings', 'total_apartments')
    op.drop_index(op.f('ix_company_profiles_user_id'), table_name='company_profiles')
    op.drop_index(op.f('ix_company_profiles_id'), table_name='company_profiles')
    op.drop_table('company_profiles')
    # ### end Alembic commands ###
