"""price_history_agent_review_virtual_tour

Revision ID: d9f0956bc056
Revises: 10f1f19fe789
Create Date: 2026-06-19 21:18:57.202179
"""
from alembic import op
import sqlalchemy as sa


revision = 'd9f0956bc056'
down_revision = '10f1f19fe789'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agent_reviews',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('agent_id', sa.Integer(), nullable=False),
    sa.Column('reviewer_id', sa.Integer(), nullable=False),
    sa.Column('rating', sa.Float(), nullable=False),
    sa.Column('comment', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['agent_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['reviewer_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_agent_reviews_agent_id'), 'agent_reviews', ['agent_id'], unique=False)
    op.create_index(op.f('ix_agent_reviews_id'), 'agent_reviews', ['id'], unique=False)
    op.create_table('price_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('property_id', sa.Integer(), nullable=False),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('recorded_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['property_id'], ['properties.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_price_history_id'), 'price_history', ['id'], unique=False)
    op.create_index(op.f('ix_price_history_property_id'), 'price_history', ['property_id'], unique=False)
    op.add_column('properties', sa.Column('virtual_tour_url', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('properties', 'virtual_tour_url')
    op.drop_index(op.f('ix_price_history_property_id'), table_name='price_history')
    op.drop_index(op.f('ix_price_history_id'), table_name='price_history')
    op.drop_table('price_history')
    op.drop_index(op.f('ix_agent_reviews_id'), table_name='agent_reviews')
    op.drop_index(op.f('ix_agent_reviews_agent_id'), table_name='agent_reviews')
    op.drop_table('agent_reviews')
    # ### end Alembic commands ###
